language: python
sudo: false
dist: trusty
services:
  - docker
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - gimme 1.8
  - source ~/.gimme/envs/latest.env
  - pip install --upgrade pip
  - pip install -r requirements.txt codecov
  - CC=gcc-5 CXX=g++-5 pip install -e .
script:
  - coverage run -m unittest discover
after_success:
  - codecov
notifications:
  email: false
