language: python
sudo: false
dist: trusty
services:
- docker
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/google-cloud-sdk"
python:
- '3.4'
- '3.5'
- '3.6'
before_install:
- (openssl aes-256-cbc -K $encrypted_fc69f8f90972_key -iv $encrypted_fc69f8f90972_iv
  -in .gcs.json.enc -out gcs.json -d && export secure=y) || true
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version
- if [ "$secure" = y ]; then gcloud auth activate-service-account --key-file=gcs.json; fi
install:
- gimme 1.8
- source ~/.gimme/envs/latest.env
- pip install --upgrade pip
- pip install -r requirements.txt codecov
- CC=gcc-5 CXX=g++-5 pip install -e .
script:
- coverage run -m unittest discover
after_success:
- codecov
notifications:
  email: false
